// <auto-generated />
using System;
using CHSMS.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CHSMS.API.Migrations
{
    [DbContext(typeof(SEP_TestContext))]
    partial class SEP_TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CHSMS.API.Models.ExternalPrescription", b =>
                {
                    b.Property<int>("ExternalPrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExternalPrescriptionID");

                    b.Property<bool?>("IsBhyt")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsBHYT");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<int>("MedicalRecordHistoryId")
                        .HasColumnType("int")
                        .HasColumnName("MedicalRecordHistoryID");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ExternalPrescriptionId");

                    b.HasIndex("MedicalRecordHistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ExternalPrescription", (string)null);
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicalRecord", b =>
                {
                    b.Property<int>("MedicalRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicalRecordID");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EthnicGroup")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("HealthInsurance")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Job")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PatientName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MedicalRecordId");

                    b.ToTable("MedicalRecord", (string)null);
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicalRecordHistory", b =>
                {
                    b.Property<int>("MedicalRecordHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicalRecordHistoryID");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BloodPressure")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("DiagnoseConclusion")
                        .HasColumnType("longtext");

                    b.Property<string>("DiseaseProgress")
                        .HasColumnType("longtext");

                    b.Property<string>("DiseaseStage")
                        .HasColumnType("longtext");

                    b.Property<double?>("Height")
                        .HasColumnType("double");

                    b.Property<string>("Icd")
                        .HasColumnType("longtext")
                        .HasColumnName("ICD");

                    b.Property<double?>("InsuranceExemption")
                        .HasColumnType("double");

                    b.Property<string>("MedicalOrder")
                        .HasColumnType("longtext");

                    b.Property<string>("MedicalRecordHistoryCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int")
                        .HasColumnName("MedicalRecordID");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("PatientCategory")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("Pulse")
                        .HasColumnType("double");

                    b.Property<double?>("RespiratoryRate")
                        .HasColumnType("double");

                    b.Property<string>("Symptom")
                        .HasColumnType("longtext");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double");

                    b.Property<string>("TreatmentBed")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("TreatmentMethod")
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<double?>("Weight")
                        .HasColumnType("double");

                    b.HasKey("MedicalRecordHistoryId");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("UserId");

                    b.ToTable("MedicalRecordHistory", (string)null);
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicalSupply", b =>
                {
                    b.Property<int>("MedicalSupplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicalSupplyID");

                    b.Property<int?>("BidNumber")
                        .HasColumnType("int");

                    b.Property<double?>("ImportPrice")
                        .HasColumnType("double");

                    b.Property<string>("MedicalSupplyCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MedicalSupplyName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<double?>("SellingPrice")
                        .HasColumnType("double");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    b.Property<string>("SupplyType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MedicalSupplyId");

                    b.HasIndex("SupplierId");

                    b.ToTable("MedicalSupplies");
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicalSupplyConsumption", b =>
                {
                    b.Property<int>("MsconsumptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MSConsumptionId");

                    b.Property<double?>("Amount")
                        .HasColumnType("double");

                    b.Property<DateTime?>("ConsumptionDate")
                        .HasColumnType("date");

                    b.Property<int>("MedicalSupplyInventoryId")
                        .HasColumnType("int")
                        .HasColumnName("MedicalSupplyInventoryID");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MsconsumptionId");

                    b.HasIndex("MedicalSupplyInventoryId");

                    b.ToTable("MedicalSupplyConsumption", (string)null);
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicalSupplyInventory", b =>
                {
                    b.Property<int>("SupplyInventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplyInventoryID");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CertificateNumber")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<double?>("ImportQuantity")
                        .HasColumnType("double");

                    b.Property<DateTime?>("ManufactureDate")
                        .HasColumnType("date");

                    b.Property<int>("MedicalSupplyId")
                        .HasColumnType("int")
                        .HasColumnName("MedicalSupplyID");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<double?>("Quantity")
                        .HasColumnType("double");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<bool?>("TransactionType")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("SupplyInventoryId")
                        .HasName("PK__MedicalS__8C3DCF4A17054FB0");

                    b.HasIndex("MedicalSupplyId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("MedicalSupplyInventory", (string)null);
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicalSupplyInventoryStatistic", b =>
                {
                    b.Property<int>("Msisid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MSISID");

                    b.Property<double>("ActualQuantity")
                        .HasColumnType("double");

                    b.Property<DateTime?>("ConfirmDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ConfirmPerson")
                        .HasColumnType("int");

                    b.Property<bool>("IsUpdate")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MsinventoryId")
                        .HasColumnType("int")
                        .HasColumnName("MSInventoryID");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<double>("Quantity")
                        .HasColumnType("double");

                    b.Property<DateTime>("StatisticDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StatisticPerson")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("Msisid");

                    b.HasIndex("MsinventoryId");

                    b.ToTable("MedicalSupplyInventoryStatistics");
                });

            modelBuilder.Entity("CHSMS.API.Models.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    b.Property<string>("ActiveIngredient")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BidNumber")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Dosage")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DosageForm")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<double?>("ImportPrice")
                        .HasColumnType("double");

                    b.Property<bool?>("IsBhyt")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsBHYT");

                    b.Property<string>("MedicineCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MedicineName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<double?>("SellingPrice")
                        .HasColumnType("double");

                    b.Property<int?>("ShelfLife")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MedicineId");

                    b.ToTable("Medicine", (string)null);
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicineConsumption", b =>
                {
                    b.Property<int>("MedicineConsumptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicineConsumptionID");

                    b.Property<double?>("Amount")
                        .HasColumnType("double");

                    b.Property<DateTime?>("ConsumptionDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsSpecialMedicine")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MedicineInventoryId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineInventoryID");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MedicineConsumptionId");

                    b.HasIndex("MedicineInventoryId");

                    b.ToTable("MedicineConsumption", (string)null);
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicineInventory", b =>
                {
                    b.Property<int>("MedicineInventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicineInventoryID");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CertificateNumber")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<double?>("ImportQuantity")
                        .HasColumnType("double");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("datetime");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<double?>("Quantity")
                        .HasColumnType("double");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<bool?>("TransactionType")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MedicineInventoryId");

                    b.HasIndex("MedicineId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SupplierId");

                    b.ToTable("MedicineInventory", (string)null);
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicineInventoryStatistic", b =>
                {
                    b.Property<int>("MedicineInventoryId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineInventoryID");

                    b.Property<double>("ActualQuantity")
                        .HasColumnType("double");

                    b.Property<DateTime?>("ConfirmDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ConfirmPerson")
                        .HasColumnType("int");

                    b.Property<bool>("IsUpdate")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MedicineInventoryStatisticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicineInventoryStatisticsID");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<double>("Quantity")
                        .HasColumnType("double");

                    b.Property<DateTime>("StatisticDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StatisticPerson")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("MedicineInventoryId");

                    b.ToTable("MedicineInventoryStatistics");
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicinePrescription", b =>
                {
                    b.Property<int>("ExternalPrescriptionId")
                        .HasColumnType("int")
                        .HasColumnName("ExternalPrescriptionID");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.HasKey("ExternalPrescriptionId", "MedicineId");

                    b.HasIndex("MedicineId");

                    b.ToTable("Medicine_Prescription", (string)null);
                });

            modelBuilder.Entity("CHSMS.API.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionID");

                    b.Property<bool?>("IsBhyt")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsBHYT");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<int>("MedicalRecordHistoryId")
                        .HasColumnType("int")
                        .HasColumnName("MedicalRecordHistoryID");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("MedicalRecordHistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("CHSMS.API.Models.PrescriptionMedicineConsumption", b =>
                {
                    b.Property<int>("MedicineConsumtionId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineConsumtionID");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionID");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("double");

                    b.HasKey("MedicineConsumtionId", "PrescriptionId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("Prescription_MedicineConsumption", (string)null);
                });

            modelBuilder.Entity("CHSMS.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("RoleName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CHSMS.API.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("CHSMS.API.Models.UseMedicalSuppliesMedicalSupplyConsumption", b =>
                {
                    b.Property<int>("MsconsumptionId")
                        .HasColumnType("int")
                        .HasColumnName("MSConsumptionId");

                    b.Property<int>("UseMedicalSupplieId")
                        .HasColumnType("int")
                        .HasColumnName("UseMedicalSupplieID");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("double");

                    b.HasKey("MsconsumptionId", "UseMedicalSupplieId");

                    b.HasIndex("UseMedicalSupplieId");

                    b.ToTable("UseMedicalSupplies_MedicalSupplyConsumption", (string)null);
                });

            modelBuilder.Entity("CHSMS.API.Models.UseMedicalSupply", b =>
                {
                    b.Property<int>("UseMedicalSupplieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UseMedicalSupplieID");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<int>("MedicalRecordHistoryId")
                        .HasColumnType("int")
                        .HasColumnName("MedicalRecordHistoryID");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("UseMedicalSupplieId");

                    b.HasIndex("MedicalRecordHistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("UseMedicalSupplies");
                });

            modelBuilder.Entity("CHSMS.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Fullname")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Specialization")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CHSMS.API.Models.ExternalPrescription", b =>
                {
                    b.HasOne("CHSMS.API.Models.MedicalRecordHistory", "MedicalRecordHistory")
                        .WithMany("ExternalPrescriptions")
                        .HasForeignKey("MedicalRecordHistoryId")
                        .IsRequired()
                        .HasConstraintName("FK_ExternalPrescription_MedicalRecordHistory");

                    b.HasOne("CHSMS.API.Models.User", "User")
                        .WithMany("ExternalPrescriptions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ExternalPrescription_Users");

                    b.Navigation("MedicalRecordHistory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicalRecordHistory", b =>
                {
                    b.HasOne("CHSMS.API.Models.MedicalRecord", "MedicalRecord")
                        .WithMany("MedicalRecordHistories")
                        .HasForeignKey("MedicalRecordId")
                        .IsRequired()
                        .HasConstraintName("FK_MedicalRecordHistory_MedicalRecord");

                    b.HasOne("CHSMS.API.Models.User", "User")
                        .WithMany("MedicalRecordHistories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_MedicalRecordHistory_Users");

                    b.Navigation("MedicalRecord");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicalSupply", b =>
                {
                    b.HasOne("CHSMS.API.Models.Supplier", "Supplier")
                        .WithMany("MedicalSupplies")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK__MedicalSu__Suppl__49C3F6B7");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicalSupplyConsumption", b =>
                {
                    b.HasOne("CHSMS.API.Models.MedicalSupplyInventory", "MedicalSupplyInventory")
                        .WithMany("MedicalSupplyConsumptions")
                        .HasForeignKey("MedicalSupplyInventoryId")
                        .IsRequired()
                        .HasConstraintName("FK_MedicalSupplyConsumption_MedicalSupplyInventory1");

                    b.Navigation("MedicalSupplyInventory");
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicalSupplyInventory", b =>
                {
                    b.HasOne("CHSMS.API.Models.MedicalSupply", "MedicalSupply")
                        .WithMany("MedicalSupplyInventories")
                        .HasForeignKey("MedicalSupplyId")
                        .IsRequired()
                        .HasConstraintName("FK__MedicalSu__Medic__4CA06362");

                    b.HasOne("CHSMS.API.Models.User", "Receiver")
                        .WithMany("MedicalSupplyInventories")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK_MedicalSupplyInventory_Users");

                    b.Navigation("MedicalSupply");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicalSupplyInventoryStatistic", b =>
                {
                    b.HasOne("CHSMS.API.Models.MedicalSupplyInventory", "Msinventory")
                        .WithMany("MedicalSupplyInventoryStatistics")
                        .HasForeignKey("MsinventoryId")
                        .IsRequired()
                        .HasConstraintName("FK_MedicalSupplyInventoryStatistics_MedicalSupplyInventory");

                    b.Navigation("Msinventory");
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicineConsumption", b =>
                {
                    b.HasOne("CHSMS.API.Models.MedicineInventory", "MedicineInventory")
                        .WithMany("MedicineConsumptions")
                        .HasForeignKey("MedicineInventoryId")
                        .IsRequired()
                        .HasConstraintName("FK_MedicineConsumption_MedicineInventory");

                    b.Navigation("MedicineInventory");
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicineInventory", b =>
                {
                    b.HasOne("CHSMS.API.Models.Medicine", "Medicine")
                        .WithMany("MedicineInventories")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK__MedicalIn__Medic__5DCAEF64");

                    b.HasOne("CHSMS.API.Models.User", "Receiver")
                        .WithMany("MedicineInventories")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK_MedicineInventory_Users");

                    b.HasOne("CHSMS.API.Models.Supplier", "Supplier")
                        .WithMany("MedicineInventories")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK_MedicineInventory_Suppliers");

                    b.Navigation("Medicine");

                    b.Navigation("Receiver");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicineInventoryStatistic", b =>
                {
                    b.HasOne("CHSMS.API.Models.MedicineInventory", "MedicineInventory")
                        .WithMany()
                        .HasForeignKey("MedicineInventoryId")
                        .IsRequired()
                        .HasConstraintName("FK_MedicineInventoryStatistics_MedicineInventory");

                    b.Navigation("MedicineInventory");
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicinePrescription", b =>
                {
                    b.HasOne("CHSMS.API.Models.ExternalPrescription", "ExternalPrescription")
                        .WithMany()
                        .HasForeignKey("ExternalPrescriptionId")
                        .IsRequired()
                        .HasConstraintName("FK_Medicine_Prescription_ExternalPrescription");

                    b.HasOne("CHSMS.API.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK_Medicine_Prescription_Medicine");

                    b.Navigation("ExternalPrescription");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("CHSMS.API.Models.Prescription", b =>
                {
                    b.HasOne("CHSMS.API.Models.MedicalRecordHistory", "MedicalRecordHistory")
                        .WithMany("Prescriptions")
                        .HasForeignKey("MedicalRecordHistoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Prescriptions_MedicalRecordHistory");

                    b.HasOne("CHSMS.API.Models.User", "User")
                        .WithMany("Prescriptions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Prescript__UserI__5535A963");

                    b.Navigation("MedicalRecordHistory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHSMS.API.Models.PrescriptionMedicineConsumption", b =>
                {
                    b.HasOne("CHSMS.API.Models.MedicineConsumption", "MedicineConsumtion")
                        .WithMany()
                        .HasForeignKey("MedicineConsumtionId")
                        .IsRequired()
                        .HasConstraintName("FK_Prescription_MedicineConsumption_MedicineConsumption");

                    b.HasOne("CHSMS.API.Models.Prescription", "Prescription")
                        .WithMany()
                        .HasForeignKey("PrescriptionId")
                        .IsRequired()
                        .HasConstraintName("FK_Prescription_MedicineConsumption_Prescriptions");

                    b.Navigation("MedicineConsumtion");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("CHSMS.API.Models.UseMedicalSuppliesMedicalSupplyConsumption", b =>
                {
                    b.HasOne("CHSMS.API.Models.MedicalSupplyConsumption", "Msconsumption")
                        .WithMany()
                        .HasForeignKey("MsconsumptionId")
                        .IsRequired()
                        .HasConstraintName("FK_UseMedicalSupplies_MedicalSupplyConsumption_MedicalSupplyConsumption");

                    b.HasOne("CHSMS.API.Models.UseMedicalSupply", "UseMedicalSupplie")
                        .WithMany()
                        .HasForeignKey("UseMedicalSupplieId")
                        .IsRequired()
                        .HasConstraintName("FK_UseMedicalSupplies_MedicalSupplyConsumption_UseMedicalSupplies");

                    b.Navigation("Msconsumption");

                    b.Navigation("UseMedicalSupplie");
                });

            modelBuilder.Entity("CHSMS.API.Models.UseMedicalSupply", b =>
                {
                    b.HasOne("CHSMS.API.Models.MedicalRecordHistory", "MedicalRecordHistory")
                        .WithMany("UseMedicalSupplies")
                        .HasForeignKey("MedicalRecordHistoryId")
                        .IsRequired()
                        .HasConstraintName("FK_UseMedicalSupplies_MedicalRecordHistory");

                    b.HasOne("CHSMS.API.Models.User", "User")
                        .WithMany("UseMedicalSupplies")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UseMedicalSupplies_Users");

                    b.Navigation("MedicalRecordHistory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHSMS.API.Models.User", b =>
                {
                    b.HasOne("CHSMS.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Users__RoleID__5812160E");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicalRecord", b =>
                {
                    b.Navigation("MedicalRecordHistories");
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicalRecordHistory", b =>
                {
                    b.Navigation("ExternalPrescriptions");

                    b.Navigation("Prescriptions");

                    b.Navigation("UseMedicalSupplies");
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicalSupply", b =>
                {
                    b.Navigation("MedicalSupplyInventories");
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicalSupplyInventory", b =>
                {
                    b.Navigation("MedicalSupplyConsumptions");

                    b.Navigation("MedicalSupplyInventoryStatistics");
                });

            modelBuilder.Entity("CHSMS.API.Models.Medicine", b =>
                {
                    b.Navigation("MedicineInventories");
                });

            modelBuilder.Entity("CHSMS.API.Models.MedicineInventory", b =>
                {
                    b.Navigation("MedicineConsumptions");
                });

            modelBuilder.Entity("CHSMS.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CHSMS.API.Models.Supplier", b =>
                {
                    b.Navigation("MedicalSupplies");

                    b.Navigation("MedicineInventories");
                });

            modelBuilder.Entity("CHSMS.API.Models.User", b =>
                {
                    b.Navigation("ExternalPrescriptions");

                    b.Navigation("MedicalRecordHistories");

                    b.Navigation("MedicalSupplyInventories");

                    b.Navigation("MedicineInventories");

                    b.Navigation("Prescriptions");

                    b.Navigation("UseMedicalSupplies");
                });
#pragma warning restore 612, 618
        }
    }
}
